name: Docker Compose Integration

on:
  push:

jobs:
  validate_and_test_config_files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [docker-compose-prod.yml, docker-compose-test.yml]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Validate ${{ matrix.file }}
        run: |
          docker-compose -f ${{ matrix.file }} config --quiet
      - name: Check if ${{ matrix.file }} works as expected
        run: |
          docker-compose -f ${{ matrix.file }} up -d
      - name: List all containers
        run: |
          docker ps -a
      - name: List all images
        run: |
          docker images
      - name: List all networks
        run: |
          docker network ls